{% set name = "pari_jupyter" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: ed7af3d291c8b4906518c075bbdd60a2da6b22a32c82286985d9e132c6de78c6

build:
  number: 4
  script:
    # Remove old cythonized files
    - rm PARIKernel/svg.c PARIKernel/kernel.c PARIKernel/io.c
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - pari
    - readline
  run:
    - python
    - pari
    - readline

test:
  imports:
    - PARIKernel

about:
  home: https://github.com/sagemath/pari_jupyter
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Jupyter kernel for PARI/GP
  dev_url: https://github.com/sagemath/pari_jupyter

extra:
  recipe-maintainers:
    - conda-forge/pari
