{% set name = "pari_jupyter" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 7447842a051531cd904968c3d50573d057adb70051249f3cee3103fce2b2177d

build:
  number: 2
  script:
    # Remove old cythonized files
    - rm PARIKernel/svg.c PARIKernel/kernel.c PARIKernel/io.c
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  skip: true  # [py>312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython <3
    - pip
    - setuptools
    - pari
    - readline
  run:
    - python
    - pari
    - readline

test:
  imports:
    - PARIKernel

about:
  home: https://github.com/sagemath/pari_jupyter
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Jupyter kernel for PARI/GP
  dev_url: https://github.com/sagemath/pari_jupyter

extra:
  recipe-maintainers:
    - conda-forge/pari
