travis:
  secure:
    BINSTAR_TOKEN: o8wwJW0cAvNZZ84d1bSifUO9pVXEAPGhyc316Hw8IqzfnqSnd1P7uh0kUzcST9dlQ+MxDPjtDXRlsILVEaZ1BsTxrpdt1suMWM8V+Pqf4SPmk6F3tlSxBdJAcRUav5w6drkK452c8MWRsp1W2yHQLH2Xcdu0iavbgj4h5tqjdci94scRDxuF3ZHaMXdsaU+9J9YHYdtbrYlS6GzwbT5QILC8ubiCMPFu/NsR6VTUycI0J8sOON8yd9Seagr5c9T6PBeybn1CKgwoXdTSSTNC7+NnFpUkirONVKMr2JW+6lPzgoYdL57OdTqvt0GvL0tNZ5nvgeBSUJpPN0KbBuQymdJ1WdoOCkxJ8H0G7ZyL77hyFMJbICTcJVKLjnMxP2ECk531lCpyKo9YnywUCord8M8nNDohqej2VlOQ0AfIM7JdJBILCKC7GqoFi5BfTvzPdckTAESxESTTTjo/ZMhr+FypaubClx+BHmDuG90chsZ1dQbgz3v3RDKD4NQIZuH5P9MinSdHT6lSFUWgUlxk6cgSzj7ofLovupkDOAGF/YHZX6T4Vp56ffaBY/u2kKAq4UogQIs7/OcxpcvvZqpQLwwAAttrks7PR37CcGLCCMPpuFApZU20ze0b1hM6BSer29v4j7isTSORC9mytlyHCniNOrQqrM0hZlHw/zLZG9E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
